Class regression
meyer-lab/systemsSerology pull request #22
Opened 2020-07-07 19:46 UTC by murphymadeleine21

2020-07-07 21:49 UTC, murphymadeleine21 commented
Confusion Matrix Controller vs. Progressor: [[29 16] [14 39]] 
Confusion Matrix Viremic vs. Nonviremic: [[30 16] [14 38]] 
Our numbers are smaller because they somehow use all 181 subjects for this case–I guess not getting rid of any columns that have missing data? We only use 98 subjects here. Otherwise, not sure if this seems reasonable?

2020-07-09 18:39 UTC, aarmey requested changes
Do a little cleanup, but this does look right.

2020-07-09 18:39 UTC, aarmey commented on syserol/regression.py
> +    """Predict Controller vs. Progressor"""
These should just be standard comments, not doc strings.

2020-07-09 18:39 UTC, aarmey commented on syserol/regression.py
> +    """Predict Viremic vs. Nonviremic"""
Here too.

2020-07-09 18:39 UTC, aarmey commented on syserol/regression.py
> +    Y_pred2 = np.empty(Y2.shape)
Don't need to pre-allocate `Y_pred2`

2020-07-09 18:39 UTC, aarmey commented on syserol/regression.py
> +    Y_pred1 = np.empty(Y1.shape)
Don't need to pre-allocate `Y_pred1`

2020-07-09 18:39 UTC, aarmey commented
I think they probably threw out the variables with missing data, not the subjects.

2020-07-09 19:15 UTC, murphymadeleine21 commented
Glycan only has 98 subjects, do we want to keep glycan but reduce # of subjects to 98 (what we have currently), or get rid of the glycan data to include all 181 luminex/luminex-igg data?

2020-07-09 19:19 UTC, aarmey commented
Here, I'd like to match what they did. I'm guessing they threw out the glycans then.

2020-07-09 19:42 UTC, murphymadeleine21 commented
Confusion Matrix Controller vs. Progressor: [[53 32][24 72]] 
Confusion Matrix Viremic vs. Nonviremic: [[62 27][20 72]] 
This is pretty close to what they have.

2020-07-09 20:05 UTC, aarmey approved these changes

2020-07-09 20:21 UTC, merged