Set up cross validation script
meyer-lab/systemsSerology pull request #43
Opened 2020-08-04 22:02 UTC by murphymadeleine21

2020-08-04 22:11 UTC, aarmey requested changes

2020-08-04 22:11 UTC, aarmey commented on syserol/model.py
> +        _, matrixFac, _ = perform_CMTF(cube, copy, 10)  # run decomposition on new matrix
Make the number of components an argument to the function. You may want to run this for varied numbers.

2020-08-04 22:11 UTC, aarmey commented on syserol/model.py
>  def cross_validation():
Need a better name.

2020-08-04 23:05 UTC, murphymadeleine21 commented
We could also potentially have the script run with all of the different component numbers and write out all of the files? But that would take a very long time..

2020-08-04 23:10 UTC, aarmey commented
Not for now.

2020-08-10 16:58 UTC, murphymadeleine21 commented
I'm pretty sure I addressed all of the changes you wanted for this PR, if we want to merge.

2020-08-10 17:02 UTC, aarmey approved these changes

2020-08-10 19:28 UTC, merged