remove functions
meyer-lab/systemsSerology pull request #57
Opened 2020-08-25 18:31 UTC by murphymadeleine21

The reason I simply added a drop line instead of removing the adding of functions is because the dfGlycan originally only has 98 subjects. To keep the glyCube still 181x25, with NaNs filled where there are no glycan measurements, we can just drop the functions from the merged matrix. However, it's probably not the cleanest way to do it. I'm looking into just never adding the functions and filling with NaNs a different way but running into some strange problems with the DF.

2020-08-25 23:35 UTC, aarmey requested changes
Simplified the data import a bit. Can you fix Figure 9?

2020-08-25 23:48 UTC, murphymadeleine21 commented
Yes, I have been working on Figure9 and I think I've almost got it fixed. It's tricky with the leftout Alter subjects.

2020-08-26 00:08 UTC, murphymadeleine21 commented
Currently, when I try to make figure9 I get a weird error that I don't fully understand, because the error isn't present when I run the code in my notebook. Let me know if you see it on Jenkins and know what the error message might be about.

2020-08-26 00:13 UTC, murphymadeleine21 commented
Nevermind, looks like that issue was a simple re-naming issue I overlooked.

2020-08-26 02:32 UTC, aarmey requested changes
[This is the section causing problems](https://github.com/meyer-lab/systemsSerology/blob/noFunctionsGlycube/syserol/figures/figure10.py#L194-L200). It's because figure 10 is expecting to plot the function measurements. You can just take this out from the plot. I'm guessing that will make this build.

2020-08-26 17:27 UTC, aarmey commented
Perfect, thanks!

2020-08-26 17:27 UTC, merged